[2024-06-16T06:39:04.345+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T06:39:04.461+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rand_request.load_to_s3 scheduled__2024-06-16T05:05:00+00:00 [queued]>
[2024-06-16T06:39:04.474+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rand_request.load_to_s3 scheduled__2024-06-16T05:05:00+00:00 [queued]>
[2024-06-16T06:39:04.475+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-16T06:39:04.759+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-06-16 05:05:00+00:00
[2024-06-16T06:39:04.841+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'rand_request', 'load_to_s3', 'scheduled__2024-06-16T05:05:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/rand.py', '--cfg-path', '/tmp/tmpm24dyb1v']
[2024-06-16T06:39:04.848+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask load_to_s3
[2024-06-16T06:39:04.847+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=9316) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-16T06:39:04.859+0000] {standard_task_runner.py:63} INFO - Started process 9346 to run task
[2024-06-16T06:39:05.466+0000] {task_command.py:426} INFO - Running <TaskInstance: rand_request.load_to_s3 scheduled__2024-06-16T05:05:00+00:00 [running]> on host d4d3ae2e009b
[2024-06-16T06:39:06.715+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='rand_request' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T05:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-16T05:05:00+00:00'
[2024-06-16T06:39:06.717+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T06:39:06.826+0000] {base.py:84} INFO - Using connection ID 'simple_store' for task execution.
[2024-06-16T06:39:06.827+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='simple_store', conn_type='aws') credentials retrieved from login and password.
[2024-06-16T06:39:10.090+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-16T06:39:10.091+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T06:39:10.106+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=rand_request, task_id=load_to_s3, run_id=scheduled__2024-06-16T05:05:00+00:00, execution_date=20240616T050500, start_date=20240616T063904, end_date=20240616T063910
[2024-06-16T06:39:11.377+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-16T06:39:11.565+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T06:39:12.199+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
