[2024-06-15T21:02:12.992+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-15T21:02:13.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ran_info_api.format_response scheduled__2024-06-15T19:05:00+00:00 [queued]>
[2024-06-15T21:02:13.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ran_info_api.format_response scheduled__2024-06-15T19:05:00+00:00 [queued]>
[2024-06-15T21:02:13.035+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-06-15T21:02:13.126+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): format_response> on 2024-06-15 19:05:00+00:00
[2024-06-15T21:02:13.141+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7495) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-15T21:02:13.143+0000] {standard_task_runner.py:63} INFO - Started process 7497 to run task
[2024-06-15T21:02:13.140+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ran_info_api', 'format_response', 'scheduled__2024-06-15T19:05:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/rand_request_api.py', '--cfg-path', '/tmp/tmpcv_wa5_6']
[2024-06-15T21:02:13.144+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask format_response
[2024-06-15T21:02:13.263+0000] {task_command.py:426} INFO - Running <TaskInstance: ran_info_api.format_response scheduled__2024-06-15T19:05:00+00:00 [running]> on host d4d3ae2e009b
[2024-06-15T21:02:13.517+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='ran_info_api' AIRFLOW_CTX_TASK_ID='format_response' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T19:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-15T19:05:00+00:00'
[2024-06-15T21:02:13.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-15T21:02:13.552+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-15T21:02:13.554+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rand_request_api.py", line 17, in format_response
    result = res['results'][0]
             ~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-06-15T21:02:13.585+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ran_info_api, task_id=format_response, run_id=scheduled__2024-06-15T19:05:00+00:00, execution_date=20240615T190500, start_date=20240615T210213, end_date=20240615T210213
[2024-06-15T21:02:13.891+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task format_response (string indices must be integers, not 'str'; 7497)
[2024-06-15T21:02:13.962+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-15T21:02:14.002+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-15T21:02:14.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
